### ISSUE TITLE
Can not find tensor_product function

### ISSUE THREAD

**Issue by Pantoria** [nickdisca/DG_code#1]
Hi there,
I cannot find tensor_product function in your drive.m file, could you please add it in your repository? Thanks a lot for your time.

**Comment by nickdisca** [comment]
Hi,
I just saw your request. I have added the missing file, and I did a partial cleanup of the files/scripts. The previous version is still available in the `Old version' folder.

**Comment by Pantoria** [comment]
Dear nickdisca


I am very glad to hear from you and for your completion of the code.&nbsp;
Thanks a lot for your time


Francis




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nickdisca"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月27日(星期五) 下午3:32
收件人:&nbsp;"nickdisca/DG_code"<DG_code@noreply.github.com&gt;;
抄送:&nbsp;"大白鲸"<1033578287@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nickdisca/DG_code] Can not find tensor_product function (#1)




Hi,
 I just saw your request. I have added the missing file, and I did a partial cleanup of the files/scripts. The previous version is still available in the `Old version' folder.
